Class OMOP.Response.prestepsGetLocationAndSiteDataBP Extends Ens.Response
{

Property items As list Of OMOP.Proxy.prestepsGetLocationAndSiteDataItem;

Storage Default
{
<Data name="prestepsGetLocationAndSiteDataBPDefaultData">
<Subscript>"prestepsGetLocationAndSiteDataBP"</Subscript>
<Value name="1">
<Value>items</Value>
</Value>
</Data>
<DefaultData>prestepsGetLocationAndSiteDataBPDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
