Class OMOP.Response.prestepsGetProviderDataBP Extends Ens.Response
{

Property items As list Of OMOP.Proxy.prestepsGetProviderDataItem;

Storage Default
{
<Data name="prestepsGetProviderDataBPDefaultData">
<Subscript>"prestepsGetProviderDataBP"</Subscript>
<Value name="1">
<Value>items</Value>
</Value>
</Data>
<DefaultData>prestepsGetProviderDataBPDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
